// Authentication
export const FETCH_USER = 'FETCH_USER';

// Appearance
export const SWITCH_APPEARANCE = 'CHANGE_APPEARANCE';
export const DISPLAY_LIST_CHARACTERS = 'DISPLAY_LIST_CHARACTERS';
export const DISPLAY_LIST_CHARACTERS_WITH_FILTER = 'DISPLAY_LIST_CHARACTERS_WITH_FILTER';

// Character
export const DISPLAY_INFO_CHARACTER = 'DISPLAY_INFO_CHARACTER';
export const ADD_FAVORITE_CHARACTER = 'ADD_FAVORITE_CHARACTER';
export const DELETE_FAVORITE_CHARACTER = 'DELETE_FAVORITE_CHARACTER';
